#!/bin/bash
VERSION="0.XY"
TEMP="/var/tmp"
CUR=${PWD};

# cleaning
rm -rf /var/tmp/docbook2odf-* 2> /dev/null
rm docbook2odf-*.tar 2> /dev/null
rm docbook2odf-*.tar.gz 2> /dev/null

# make distribution directory
mkdir ${TEMP}/docbook2odf-${VERSION}
cp -r . ${TEMP}/docbook2odf-${VERSION}/
cd ${TEMP};
tar -cvf ${CUR}/docbook2odf-${VERSION}.tar docbook2odf-${VERSION} --exclude .svn -C ${TEMP}
cd ${CUR};

# gzip
gzip docbook2odf-${VERSION}.tar

# cleaning
rm -rf ${TEMP}/docbook2odf-${VERSION}
