#!/bin/bash

#VERSION=$1
VERSION=`svn info | awk '/^Revision:/ {print $2/1000}'`
TEMP="/tmp"
cd ..
CUR=${PWD};

# cleaning
rm -rf /var/tmp/docbook2odf-* 2> /dev/null
rm docbook2odf-*.tar 2> /dev/null
rm docbook2odf-*.tar.gz 2> /dev/null

# make distribution directory
mkdir ${TEMP}/docbook2odf-${VERSION}
cp -r . ${TEMP}/docbook2odf-${VERSION}/
cd ${TEMP};
tar -cvf ${CUR}/docbook2odf-${VERSION}.tar docbook2odf-${VERSION} --exclude .svn --exclude release -C ${TEMP}
cd ${CUR};

# gzip
gzip docbook2odf-${VERSION}.tar

# cleaning
rm -rf ${TEMP}/docbook2odf-${VERSION}
