.TH docbook2odf 1  "July 1, 2006" "version 0.47" "USER COMMANDS"
.SH NAME
docbook2odf \- Convert docbook document to Oasis Open Document
.SH SYNOPSIS
.B docbook2odf
[\-\-help] \-\-input\-file [\-\-output\-file]
.SH DESCRIPTION
Docbook2odf is a toolkit that automaticaly converts DocBook to OASIS OpenDocument. Conversion is based on a XSLT which makes it easy to convert DocBook\->ODF, ODT, ODS and ODP as all these documents are XML based.
.PP
The result is provided in a one zipped ODF file \(.odt/.odp/.ods\) with all required content. There are group of utilities like docbook2odt, docbook2ods and docbook2odp as docbook2odf is actually universally converting to these respective formats.
.SH OPTIONS
.TP
\-V
display the version of docbok2odf and exit.
.TP
\-\-input\-file
specify input docbook filename.
.TP
\-\-output\-file
specify output opendocument filename.
.TP
\-\-force
overwrite existing output filename.
.TP
\-\-debug
show debug messages.
.TP
\-\-quiet
quiet (no output).
.TP
\-\-help
prints short help.
.SH AUTHOR
Roman Fordinal (fordinal (at) webcom.sk)